### ISSUE TITLE
[Usage]: remove_by_regex on Python

### ISSUE THREAD

**Issue by khuonglmhw** [kvcache-ai/Mooncake#860]
### Describe your usage question

In the official doc, I see this code snippet which shows that mooncake support remove by regex:

```python
# Remove all keys starting with "user_session_"
count = store.remove_by_regex("^user_session_.*")
if count >= 0:
    print(f"Removed {count} objects")
```

however, I tried a simple test on python with mooncake version 0.3.5 (installed via pip). it shows that method does not exist.

```
AttributeError: 'mooncake.store.MooncakeDistributedStore' object has no attribute 'remove_by_regex'
```

Could anyone confirm this?
Thank you.

### Before submitting a new issue...

- [ ] Make sure you already searched for relevant issues and read the [documentation](https://kvcache-ai.github.io/Mooncake/)

**Comment by xiaguan** [comment]
bump to 0.3.6

**Comment by khuonglmhw** [comment]
After bumping to 0.3.6, I tried this code

```python
from mooncake.store import MooncakeDistributedStore

# 1. Create store instance
store = MooncakeDistributedStore()

# 2. Setup with all required parameters
store.setup(
    "localhost:12345",           # Your node's address
    "http://localhost:8080/metadata",    # HTTP metadata server
    512*1024*1024,          # 512MB segment size
    128*1024*1024,          # 128MB local buffer
    "tcp",                             # Use TCP (RDMA for high performance)
    "",                            # Empty for TCP, specify device for RDMA
    "localhost:50051"        # Master service
)

# 3. Store data
store.put("hello_key", b"Hello, Mooncake Store!")

# 4. Retrieve data
data = store.get("hello_key")
print(data.decode())  # Output: Hello, Mooncake Store!

# 5. Clean up
store.close()
```

it always requires RDMA.

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0918 10:17:36.327668 10664 client_metric.cpp:76] Client metrics enabled (default enabled)
I0918 10:17:36.328004 10664 transfer_engine.cpp:486] Metrics reporting is disabled (set MC_TE_METRIC=1 to enable)
I0918 10:17:36.328395 10664 client.cpp:46] client_id=12485693663012564109-16145658991690668178
I0918 10:17:36.328433 10664 client.cpp:54] Client metrics enabled but reporting disabled (interval=0)
I0918 10:17:36.328507 10664 master_client.cpp:214] Connecting to master at localhost:50051 from mooncake::ErrorCode mooncake::MasterClient::Connect(const string&)
E0918 10:17:36.330900 10664 client.cpp:318] Failed to get fsdir from master
I0918 10:17:36.330912 10664 transfer_engine.cpp:91] Transfer Engine parseHostNameWithPort. server_name: localhost port: 12345
I0918 10:17:36.331207 10664 transfer_metadata_plugin.cpp:1100] Found active interface eth0 with IP 172.17.0.3
I0918 10:17:36.331219 10664 transfer_engine.cpp:146] Transfer Engine RPC using new RPC mapping, listening on 172.17.0.3:16581
I0918 10:17:36.333179 10664 transfer_engine.cpp:185] Auto-discovering topology...
I0918 10:17:36.338164 10664 transfer_engine.cpp:200] Topology discovery complete. Found 18 HCAs.
W0918 10:17:36.350169 10664 rdma_context.cpp:433] Device mlx5_8 port not active
E0918 10:17:36.350817 10664 rdma_context.cpp:70] Failed to open device mlx5_8 on port  with GID 0
W0918 10:17:36.350903 10664 rdma_transport.cpp:420] Disable device mlx5_8
W0918 10:17:36.363818 10664 rdma_context.cpp:433] Device mlx5_9 port not active
E0918 10:17:36.364279 10664 rdma_context.cpp:70] Failed to open device mlx5_9 on port  with GID 0
W0918 10:17:36.364370 10664 rdma_transport.cpp:420] Disable device mlx5_9
W0918 10:17:36.376883 10664 rdma_context.cpp:433] Device mlx5_10 port not active
E0918 10:17:36.377331 10664 rdma_context.cpp:70] Failed to open device mlx5_10 on port  with GID 0
W0918 10:17:36.377369 10664 rdma_transport.cpp:420] Disable device mlx5_10
W0918 10:17:36.389403 10664 rdma_context.cpp:433] Device mlx5_11 port not active
E0918 10:17:36.389730 10664 rdma_context.cpp:70] Failed to open device mlx5_11 on port  with GID 0
W0918 10:17:36.389762 10664 rdma_transport.cpp:420] Disable device mlx5_11
W0918 10:17:36.397778 10664 rdma_context.cpp:433] Device mlx5_12 port not active
E0918 10:17:36.398147 10664 rdma_context.cpp:70] Failed to open device mlx5_12 on port  with GID 0
W0918 10:17:36.398201 10664 rdma_transport.cpp:420] Disable device mlx5_12
W0918 10:17:36.408684 10664 rdma_context.cpp:433] Device mlx5_13 port not active
E0918 10:17:36.409027 10664 rdma_context.cpp:70] Failed to open device mlx5_13 on port  with GID 0
W0918 10:17:36.409065 10664 rdma_transport.cpp:420] Disable device mlx5_13
W0918 10:17:36.421169 10664 rdma_context.cpp:433] Device mlx5_14 port not active
E0918 10:17:36.421551 10664 rdma_context.cpp:70] Failed to open device mlx5_14 on port  with GID 0
W0918 10:17:36.421603 10664 rdma_transport.cpp:420] Disable device mlx5_14
W0918 10:17:36.433502 10664 rdma_context.cpp:433] Device mlx5_15 port not active
E0918 10:17:36.433887 10664 rdma_context.cpp:70] Failed to open device mlx5_15 on port  with GID 0
W0918 10:17:36.433925 10664 rdma_transport.cpp:420] Disable device mlx5_15
W0918 10:17:36.446316 10664 rdma_context.cpp:433] Device mlx5_16 port not active
E0918 10:17:36.447211 10664 rdma_context.cpp:70] Failed to open device mlx5_16 on port  with GID 0
W0918 10:17:36.447244 10664 rdma_transport.cpp:420] Disable device mlx5_16
W0918 10:17:36.459457 10664 rdma_context.cpp:433] Device mlx5_17 port not active
E0918 10:17:36.460450 10664 rdma_context.cpp:70] Failed to open device mlx5_17 on port  with GID 0
W0918 10:17:36.460494 10664 rdma_transport.cpp:420] Disable device mlx5_17
W0918 10:17:36.472482 10664 rdma_context.cpp:433] Device mlx5_0 port not active
E0918 10:17:36.472999 10664 rdma_context.cpp:70] Failed to open device mlx5_0 on port  with GID 0
W0918 10:17:36.473031 10664 rdma_transport.cpp:420] Disable device mlx5_0
W0918 10:17:36.485124 10664 rdma_context.cpp:433] Device mlx5_1 port not active
E0918 10:17:36.485524 10664 rdma_context.cpp:70] Failed to open device mlx5_1 on port  with GID 0
W0918 10:17:36.485549 10664 rdma_transport.cpp:420] Disable device mlx5_1
W0918 10:17:36.493916 10664 rdma_context.cpp:433] Device mlx5_2 port not active
E0918 10:17:36.494270 10664 rdma_context.cpp:70] Failed to open device mlx5_2 on port  with GID 0
W0918 10:17:36.494287 10664 rdma_transport.cpp:420] Disable device mlx5_2
W0918 10:17:36.503595 10664 rdma_context.cpp:433] Device mlx5_3 port not active
E0918 10:17:36.503954 10664 rdma_context.cpp:70] Failed to open device mlx5_3 on port  with GID 0
W0918 10:17:36.503978 10664 rdma_transport.cpp:420] Disable device mlx5_3
W0918 10:17:36.516496 10664 rdma_context.cpp:433] Device mlx5_4 port not active
E0918 10:17:36.516903 10664 rdma_context.cpp:70] Failed to open device mlx5_4 on port  with GID 0
W0918 10:17:36.516919 10664 rdma_transport.cpp:420] Disable device mlx5_4
W0918 10:17:36.527258 10664 rdma_context.cpp:433] Device mlx5_5 port not active
E0918 10:17:36.527650 10664 rdma_context.cpp:70] Failed to open device mlx5_5 on port  with GID 0
W0918 10:17:36.527663 10664 rdma_transport.cpp:420] Disable device mlx5_5
W0918 10:17:36.539618 10664 rdma_context.cpp:433] Device mlx5_6 port not active
E0918 10:17:36.540057 10664 rdma_context.cpp:70] Failed to open device mlx5_6 on port  with GID 0
W0918 10:17:36.540082 10664 rdma_transport.cpp:420] Disable device mlx5_6
W0918 10:17:36.551853 10664 rdma_context.cpp:433] Device mlx5_7 port not active
E0918 10:17:36.552192 10664 rdma_context.cpp:70] Failed to open device mlx5_7 on port  with GID 0
W0918 10:17:36.552199 10664 rdma_transport.cpp:420] Disable device mlx5_7
E0918 10:17:36.552202 10664 rdma_transport.cpp:426] RdmaTransport: No available RNIC
E0918 10:17:36.552206 10664 rdma_transport.cpp:60] RdmaTransport: cannot initialize RDMA resources
E0918 10:17:36.552208 10664 transfer_engine.cpp:234] Failed to install RDMA transport
E0918 10:17:36.552211 10664 client.cpp:228] Failed to initialize transfer engine, rc=-1
E0918 10:17:36.552215 10664 client.cpp:341] Failed to initialize transfer engine
E0918 10:17:36.553673 10664 pybind_client.cpp:123] Failed to create client
E0918 10:17:36.553776 10664 pybind_client.cpp:230] Client is not initialized
E0918 10:17:36.553786 10664 store_py.cpp:23] Client is not initialized

E0918 10:17:36.553815 10664 pybind_client.cpp:210] Client is not initialized
```

**Comment by xiaguan** [comment]
sorry for this, you could `export MC_MS_AUTO_DISC=0"
