### PR TITLE
[Bugfix][Build] Fix S3SnapshotObjectStore Pimpl error & improve build reliability

### PR DESCRIPTION
**Pull request by timzhang0727**
## Summary

This PR contains two commits addressing build-related issues:

1. **[Bugfix] Fix Pimpl pattern compilation error in `S3SnapshotObjectStore`**
2. **[Build] Improve build reliability: yalantinglibs caching and Go network fallback**

---

### Problem

`S3SnapshotObjectStore` uses the Pimpl pattern with `std::unique_ptr<Impl>`, where `Impl` is a forward-declared incomplete type in the header. However, the destructor was declared as `= default` **in the header file** (line 23 of `s3_snapshot_object_store.h`):

```cpp
~S3SnapshotObjectStore() override = default;
```

This causes a compilation error because `std::unique_ptr` requires a complete type at the point where the deleter is instantiated. When the destructor is defaulted in the header, the compiler tries to generate the destructor code (including `unique_ptr::~unique_ptr()`) where `Impl` is still incomplete.

**Error message:**
```
error: invalid application of 'sizeof' to an incomplete type 'mooncake::S3SnapshotObjectStore::Impl'
```

### Root Cause

Introduced in PR #1757 (`[STORE] support Redis ACL username authentication and reorganize HA`) by @YiXR, merged on 2026-03-27 (commit `e1220bb`). The HA directory restructuring created `s3_snapshot_object_store.h` with an incorrect Pimpl destructor placement.

### Fix

- **Header** (`s3_snapshot_object_store.h`): Change `~S3SnapshotObjectStore() override = default;` → `~S3SnapshotObjectStore() override;` (declaration only)
- **Source** (`s3_snapshot_object_store.cpp`): Add `S3SnapshotObjectStore::~S3SnapshotObjectStore() = default;` after `Impl` class definition (where the type is complete)

This is the standard Pimpl idiom fix — the destructor must be defined in the `.cpp` file where the `Impl` type is fully visible.

### Files Changed
- `mooncake-store/include/ha/snapshot/object/backends/s3/s3_snapshot_object_store.h` (1 line)
- `mooncake-store/src/ha/snapshot/object/backends/s3/s3_snapshot_object_store.cpp` (2 lines)

---

### 2a. yalantinglibs Installation Caching

**Problem:** The original `dependencies.sh` always re-downloads and recompiles yalantinglibs from scratch, even if it is already installed on the system. This wastes significant build time in CI and development environments.

**Fix:** Detect existing installation by searching for `yalantinglibsConfig.cmake` in standard cmake paths (`/usr/local/lib/cmake`, `/usr/lib/cmake`, `/usr/local/share/cmake`):
- ✅ **Installed + version matches** → Skip with green message
- ⚠️ **Installed + version mismatch** → Warning (does NOT fail the build)
- ⚠️ **Installed + version unknown** → Skip with warning
- 🔽 **Not installed** → Download and build as before

### 2b. Go Download Mirror Fallback

**Problem:** `go.dev` may be slow or unreachable in some network environments (e.g., China mainland), causing the build to fail.

**Fix:** Try multiple mirrors in order with timeout and retry:
1. `https://go.dev/dl/` (official)
2. `https://golang.google.cn/dl/` (Google China)
3. `https://mirrors.aliyun.com/golang/` (Alibaba Cloud)

Each mirror gets `--timeout=30 --tries=2`. Only fails if **all** mirrors are unreachable.

### 2c. GOPROXY for Go Module Downloads

**Problem:** `go mod tidy` / `go build` may fail or hang when downloading Go modules in restricted network environments.

**Fix:** Set `GOPROXY=https://goproxy.cn,https://goproxy.io,direct` in all Go build locations. **Only applies when `$GOPROXY` is not already set**, respecting user's existing configuration.

Locations updated:
- `dependencies.sh` — global setup after Go installation (also persists to `~/.bashrc`)
- `mooncake-common/etcd/CMakeLists.txt` — cmake-driven etcd build
- `mooncake-common/etcd/build.sh` — manual etcd build script
- `mooncake-p2p-store/build.sh` — p2p store build script

### Files Changed
- `dependencies.sh` (major refactor of yalantinglibs + Go sections)
- `mooncake-common/etcd/CMakeLists.txt` (1 line)
- `mooncake-common/etcd/build.sh` (6 lines)
- `mooncake-p2p-store/build.sh` (5 lines)

---

## Testing

- [x] Verified Pimpl fix compiles correctly with `-DBUILD_SHARED_LIBS=ON`
- [x] Verified `dependencies.sh` logic handles all 4 yalantinglibs detection cases
- [x] Verified GOPROXY respects existing user configuration (`$GOPROXY` not overwritten if set)
- [x] Verified Go mirror fallback logic with timeout/retry

cc @YiXR (FYI for the Pimpl fix in your HA refactor)

### CODE REVIEW

**Comment by staryxchen** [comment]
[nixl PR #1485](https://github.com/ai-dynamo/nixl/pull/1485) is hitting the same issue.

**Comment by ztxdcyy** [comment]
Hi, could a maintainer please approve the CI workflows? Thanks!  @YiXR

**Comment by ztxdcyy** [comment]
> [nixl PR #1485](https://github.com/ai-dynamo/nixl/pull/1485) is hitting the same issue.

Thanks for letting me know and thanks for mention me. I found that you're addressing the same concern I've been working on — build reliability with Mooncake. Great to see others focused on this too.

Just to clarify the connection: the -DWITH_STORE=OFF flag you mentioned is actually the workaround for the S3SnapshotObjectStore Pimpl compilation error — that's exactly what our PR #1796 is fixing upstream. Once #1796 is merged, the store module should compile cleanly again and this flag can be made optional. Remove the hard code for -j4 also make sense!

**Comment by staryxchen** [comment]
> > [nixl PR #1485](https://github.com/ai-dynamo/nixl/pull/1485) is hitting the same issue.
> 
> Thanks for letting me know and thanks for mention me. I found that you're addressing the same concern I've been working on — build reliability with Mooncake. Great to see others focused on this too.
> 
> Just to clarify the connection: the -DWITH_STORE=OFF flag you mentioned is actually the workaround for the S3SnapshotObjectStore Pimpl compilation error — that's exactly what our PR #1796 is fixing upstream. Once #1796 is merged, the store module should compile cleanly again and this flag can be made optional. Remove the hard code for -j4 also make sense!

Actually, nixl doesn't need the Mooncake store module at all, so setting `-DWITH_STORE=OFF` is not just a workaround for the Pimpl compilation error — it also speeds up the build by skipping unnecessary components.

**Comment by staryxchen** [comment]
Also, it looks like there are merge conflicts that need to be resolved before this can be merged. Could you rebase or merge the latest changes from the target branch to fix them? Thanks!

**Comment by ztxdcyy** [comment]
> Also, it looks like there are merge conflicts that need to be resolved before this can be merged. Could you rebase or merge the latest changes from the target branch to fix them? Thanks!

Hi! I've rebased onto latest main and resolved the conflicts (yalantinglibs was converted to submodule by #1781, so I dropped my caching logic).

Also fixed the likely cause of the previous CI failure — I was unconditionally setting GOPROXY to CN proxies in the build scripts, which would slow down or break CI running outside China. Now removed from build scripts entirely, and in dependencies.sh it's only set when the Go download actually falls back to a CN mirror.

Could you help approve and run the CI? Thanks! 🙏
